### ISSUE TITLE
实测好用，非常感谢

### ISSUE THREAD

**Issue by toyo2333** [missuo/FreeGPT35#1]
在一些需要填写配置的敌法，key随便填，然后endpoint填写自己部署的地址即可。速度很快。

ps 以前都是只能买号，然后用不了几天就作废了。

**Comment by missuo** [comment]
Thank you for your support.

**Comment by missuo** [comment]
> > 在一些需要填写配置的地方，key随便填（我之前作废的key也ok），然后endpoint填写自己部署的地址即可。速度很快。
> > ps 以前都是只能买号，然后用不了几天就作废了。
> 
> 我试了下打不通chatgpt-next-web，你能展示下chatgpt-next-web怎么填写的吗？

<img width="946" alt="image" src="https://github.com/missuo/FreeGPT35/assets/55200481/c83302df-372d-45a5-ab8f-6fe597506ff2">

**Comment by missuo** [comment]
> > > 在一些需要填写配置的地方，key随便填（我之前作废的key也ok），然后endpoint填写自己部署的地址即可。速度很快。
> > > ps 以前都是只能买号，然后用不了几天就作废了。
> > 
> > 
> > 我试了下打不通chatgpt-next-web，你能展示下chatgpt-next-web怎么填写的吗？
> 
> 我也没打通。。。 不知道怎么填写

https://github.com/missuo/FreeGPT35#freegpt35-service-with-chatgpt-next-web

**Comment by gnsilence** [comment]
> 在一些需要填写配置的地方，key随便填（我之前作废的key也ok），然后endpoint填写自己部署的地址即可。速度很快。
> 
> ps 以前都是只能买号，然后用不了几天就作废了。

你用的啥服务器部署的，我都部署后访问速度特别慢
