### ISSUE TITLE
访问控制：增加api key设定

### ISSUE THREAD

**Issue by i2qaq** [missuo/FreeGPT35#10]
希望能自定义api key，不然容易被扫到而滥用

**Comment by missuo** [comment]
It's possible, but not necessary.

**Comment by i2qaq** [comment]
afraid to get 429 if someone else abuses my endpoint 😔

**Comment by SunnyGPT** [comment]
兄弟你是怎么部署的，怎么我用美国VPS部署仍然报错提示让我用美国VPN？

**Comment by i2qaq** [comment]
> 兄弟你是怎么部署的，怎么我用美国VPS部署仍然报错提示让我用美国VPN？

美国小鸡。。。可能你的IP不太行🤔

**Comment by SunnyGPT** [comment]
> > 兄弟你是怎么部署的，怎么我用美国VPS部署仍然报错提示让我用美国VPN？
> 
> 我也是美国小鸡。。。可能你的IP不太行🤔

用curl测试发现是机器人检查过不了，并不是无权限访问。对于你开贴的问题其实挺简单的，让GPT-4帮你写一个key验证，或者限制IP访问这个项目端口就行了。

**Comment by dannyask** [comment]
接入到oneapi不久行了，由oneapi管理key

**Comment by zzhhxx** [comment]
> > > 兄弟你是怎么部署的，怎么我用美国VPS部署仍然报错提示让我用美国VPN？
> > 
> > 
> > 我也是美国小鸡。。。可能你的IP不太行🤔
> 
> 用curl测试发现是机器人检查过不了，并不是无权限访问。对于你开贴的问题其实挺简单的，让GPT-4帮你写一个key验证，或者限制IP访问这个项目端口就行了。

如果使用反代的话，在相应的nginx配置中增添如下代码即可（写死的，也可以自己优化优化）
```
location / {
        if ($http_authorization != "Bearer your_access_token") {
            return 403; 
        }
        proxy_pass http://反代的地址;
    }
```

**Comment by huawuhen** [comment]
> afraid to get 429 if someone else abuses my endpoint

你咋想的，你部署在vps的特征是明显的，人家扫你vps就能扫到你这个服务，干嘛去管你的oneapi

**Comment by huawuhen** [comment]
> > afraid to get 429 if someone else abuses my endpoint
> 
> 你咋想的，你部署在vps的特征是明显的，人家扫你vps就能扫到你这个服务，干嘛去管你的oneapi

好吧，也许我错了。如果与oneapi部署在同一服务器上确实可行。

**Comment by missuo** [comment]
> > afraid to get 429 if someone else abuses my endpoint
> 
> 你咋想的，你部署在vps的特征是明显的，人家扫你vps就能扫到你这个服务，干嘛去管你的oneapi

He's right. Listen on 127.0.0.1.

```bash
ufw deny 3040
```

**Comment by zzhhxx** [comment]
> > > afraid to get 429 if someone else abuses my endpoint
> > 
> > 
> > 你咋想的，你部署在vps的特征是明显的，人家扫你vps就能扫到你这个服务，干嘛去管你的oneapi
> 
> 好吧，也许我错了。如果与oneapi部署在同一服务器上确实可行。

docker限制127.0.0.1，反代再加个请求头应该就没啥问题了吧
```
docker run -d \
  --restart=always \
  -p 127.0.0.1:3040:3040 \
  --name freegpt35 \
  ghcr.io/missuo/freegpt35
```

**Comment by gllgoe** [comment]
Error refreshing session ID, retrying in 1 minute... If this error persists, your country may not be supported yet. If your country was the issue, please consider using a U.S. VPN

**Comment by gllgoe** [comment]
"status":false,"error":{"message":"The requested endpoint was not found. please make sure to use \"http://localhost:3040/v1\" as the base URL.","type":"invalid_request_error"}}
