### ISSUE TITLE
It can be used normally in the web page, but an error is reported in docker under the LAN.

### ISSUE THREAD

**Issue by martint028** [missuo/FreeGPT35#12]
{"status":false,"error":{"message":"An error happened, please make sure your request is SFW, or use a jailbreak to bypass the filter.","type":"invalid_request_error"}}%

**Comment by zhanghao123321** [comment]
me too

**Comment by funv5** [comment]
me too

**Comment by SunnyGPT** [comment]
The probability of this error occurring is very high, even though the content is all SFW.

**Comment by tianlichunhong** [comment]
me too

**Comment by chris-ss** [comment]
{"status":false,"error":{"message":"The requested endpoint was not found. please make sure to use \"http://localhost:3040/v1\" as the base URL.","type":"invalid_request_error"}}

**Comment by zmk-ink** [comment]
错误导致的原因：
1, 请求头没有指定 Content-Type: application/json
2, "stream": true 的 true 首字母不能大写。

**Comment by Doutianbao** [comment]
> {"status":false,"error":{"message":"The requested endpoint was not found. please make sure to use \"http://localhost:3040/v1\" as the base URL.","type":"invalid_request_error"}}

same

**Comment by llity** [comment]
什么原因

**Comment by chris-ss** [comment]
> {"status":false,"error":{"message":"An error happened, please make sure your request is SFW, or use a jailbreak to bypass the filter.","type":"invalid_request_error"}}%

same

**Comment by hellostronger** [comment]
how to resolve this problem, thk

**Comment by Holden-Lin** [comment]
I fix this by restarting my server.
