### ISSUE TITLE
FreeGPT35(docker) + ChatGPT-Next-Web(docker) 搭建出现问题...

### ISSUE THREAD

**Issue by ijrou** [missuo/FreeGPT35#13]
docker run -d --name free_gpt --restart=always -p 3040:3040 ghcr.io/missuo/freegpt35

docker run -d --name gpt_next_web -p 3000:3000  yidadaa/chatgpt-next-web

宿主机上执行如下正确返回：
```sh
curl http://172.17.0.2:3040/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer any_string_you_like" \
  -d '{
    "model": "gpt-3.5-turbo",
    "messages": [
      {
        "role": "user",
        "content": "你好啊!"
      }
    ],
    "stream": true
    }'
```
![image](https://github.com/missuo/FreeGPT35/assets/20642702/ea0cc4ac-3d89-4c33-b774-a747cf1bb8d6)

但是部署到 chatgpt-next-web (使用域名反向代理到了chatgpt-next-web 容器)中就无法使用：
![image](https://github.com/missuo/FreeGPT35/assets/20642702/28686728-77f5-495b-8185-29f20ef370d4)

![image](https://github.com/missuo/FreeGPT35/assets/20642702/d5dd4332-5389-4c39-bf48-973ec48f94f0)

**Comment by missuo** [comment]
I noticed that the server logs have returned the Stream Response normally, indicating that the server is operating normally. Please check your **next-web** configuration.

**Comment by chunzha1** [comment]
直接使用域名好像网页版不行，另外next-web好像不需要加/v1和后面的那部分?

**Comment by alexallen1** [comment]
> I noticed that the server logs have returned the Stream Response normally, indicating that the server is operating normally. Please check your **next-web** configuration.

Can you, as a teacher, show next-web examples

**Comment by missuo** [comment]
> 增加 tls 试试 `docker-compose.yml`:
> 
> ```
> services:
>   freegpt35:
>     container_name: freegpt35
>     image: missuo/freegpt35:latest
>     
>   caddy:
>     container_name: caddy
>     image: caddy:2
>     volumes:
>       - ./Caddyfile:/etc/caddy/Caddyfile
>       - caddy_data:/data
>       - caddy_config:/config
>     ports:
>       - "80:80"
>       - "443:443"
>     depends_on:
>       - freegpt35
>       
> volumes:
>   caddy_data:
>   caddy_config:  
> ```
> 
> `Caddyfile`:
> 
> ```
> {you_domain } {
>     handle_path /gpt/* {
>         reverse_proxy freegpt35:3040
>     }
> }
> ```

This will occupy 80 443, and you won't be able to deploy **any other** web services.
