### ISSUE TITLE
请问如何保持同一个会话，是否有接口？

### ISSUE THREAD

**Issue by playbear668** [missuo/FreeGPT35#16]
目前已经实现了对话，但是无法进行会话保持，比如让GPT出3道面试题，下一个问题要答案的时候，却没办法回答上一条的答案，接口中的API是否有参数可以设置，感谢！！

**Comment by lateautumn2** [comment]
这个与本项目无关，本项目只是提供chat2api，

**Comment by playbear668** [comment]
> 这个与此项目无关，此项目只是提供chat2api，

也不能说无关，在web里直接聊天，会话是连续的，这里爬虫来的接口时候忽略了上下文了，简单粗暴

**Comment by yushangxiao** [comment]
参数传递时可以有多个信息，会话可以自己实现存储在本地。如：messages:[
        {"role": "user", "content": "你好。"},
        {"role": "assistant", "content": "你好，我能为你做些什么?"},
         {"role": "user", "content": "龙争虎斗是什么意思"}
    ]
