### ISSUE TITLE
打开网址是这样的

### ISSUE THREAD

**Issue by Doutianbao** [missuo/FreeGPT35#18]
{"status":false,"error":{"message":"The requested endpoint was not found. please make sure to use \"http://localhost:3040/v1\" as the base URL.","type":"invalid_request_error"}}

**Comment by llity** [comment]
+1

**Comment by chris-ss** [comment]
用Postman之类的API工具测试, GET是这样 改成POST.

**Comment by xinwb** [comment]
+1

**Comment by Doutianbao** [comment]
> 解决了，用docker搭建好FreeGPT35后，用域名反向代理到这个3040端口，然后这么设置：
> ![image](https://github.com/missuo/FreeGPT35/assets/20642702/700621b3-16b5-4de0-90c6-b3f37f3aa640)
> 

并没有

**Comment by missuo** [comment]
> > 解决了，用docker搭建好FreeGPT35后，用域名反向代理到这个3040端口，然后这么设置：
> > ![image](https://private-user-images.githubusercontent.com/20642702/319237736-700621b3-16b5-4de0-90c6-b3f37f3aa640.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxOTM1NTAsIm5iZiI6MTcxMjE5MzI1MCwicGF0aCI6Ii8yMDY0MjcwMi8zMTkyMzc3MzYtNzAwNjIxYjMtMTZiNS00ZGUwLTkwYzYtYjNmMzdmM2FhNjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDAxMTQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlODM5MDQ4YjRhMmYyMGZmYzU1OGVmNGM5YTM2MjM5YmYzMGRmMGRjNGExMTgxYTk0N2U5ZmIzZjI3ZDg2MjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vaCPJKt3hoaVBu9Ux9VeMwxxMBG8QXgod8SDwbBeZv4)
> 
> 并没有

I closed this issue directly because I think you should have read the README carefully before raising it. You accessed a non-existent path yourself.

**Comment by alexallen1** [comment]
> 解决了，用docker搭建好FreeGPT35后，用域名反向代理到这个3040端口，然后这么设置： ![image](https://private-user-images.githubusercontent.com/20642702/319237736-700621b3-16b5-4de0-90c6-b3f37f3aa640.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMDUwOTAsIm5iZiI6MTcxMjIwNDc5MCwicGF0aCI6Ii8yMDY0MjcwMi8zMTkyMzc3MzYtNzAwNjIxYjMtMTZiNS00ZGUwLTkwYzYtYjNmMzdmM2FhNjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDA0MjYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlNzE4NjMwNzdjNTNhYzI3YTk5ZTA0YjE4YmM1MTZkYjJlYTZhOGIxOWYxMTQ1OTU3MDM4MWYzODQwOTRkNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5mAb5_7pw4euQH3O_TeOcnHf38MgmvusdMjV3zXoAPs)

虽然这样是可以，但绕去多了几重呀，作者也不提醒一下

**Comment by missuo** [comment]
> > 解决了，用docker搭建好FreeGPT35后，用域名反向代理到这个3040端口，然后这么设置： ![image](https://private-user-images.githubusercontent.com/20642702/319237736-700621b3-16b5-4de0-90c6-b3f37f3aa640.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMDUwOTAsIm5iZiI6MTcxMjIwNDc5MCwicGF0aCI6Ii8yMDY0MjcwMi8zMTkyMzc3MzYtNzAwNjIxYjMtMTZiNS00ZGUwLTkwYzYtYjNmMzdmM2FhNjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDA0MjYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlNzE4NjMwNzdjNTNhYzI3YTk5ZTA0YjE4YmM1MTZkYjJlYTZhOGIxOWYxMTQ1OTU3MDM4MWYzODQwOTRkNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5mAb5_7pw4euQH3O_TeOcnHf38MgmvusdMjV3zXoAPs)
> 
> 虽然这样是可以，但绕去多了几重呀，作者也不提醒一下

我需要提醒什么？我让你这么绕来绕去的？你自己不会用怪作者？？？？**Docker Compose** 启动两个 **Services**，一键启动不就行了？

**Comment by alexallen1** [comment]
> > > 解决了，用docker搭建好FreeGPT35后，用域名反向代理到这个3040端口，然后这么设置： ![image](https://private-user-images.githubusercontent.com/20642702/319237736-700621b3-16b5-4de0-90c6-b3f37f3aa640.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMDUwOTAsIm5iZiI6MTcxMjIwNDc5MCwicGF0aCI6Ii8yMDY0MjcwMi8zMTkyMzc3MzYtNzAwNjIxYjMtMTZiNS00ZGUwLTkwYzYtYjNmMzdmM2FhNjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDA0MjYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlNzE4NjMwNzdjNTNhYzI3YTk5ZTA0YjE4YmM1MTZkYjJlYTZhOGIxOWYxMTQ1OTU3MDM4MWYzODQwOTRkNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5mAb5_7pw4euQH3O_TeOcnHf38MgmvusdMjV3zXoAPs)
> > 
> > 
> > 虽然这样是可以，但绕去多了几重呀，作者也不提醒一下
> 
> 我需要提醒什么？我让你这么绕来绕去的？你自己不会用怪作者？？？？**Docker Compose** 启动两个 **Services**，一键启动不就行了？自己搞不定就知道发 Issue，在这喷作者的时间，你好好把 Docker 学学明白。

你是暗示我们天生大神，自己都懂得填写接口地址啊。楼上都要反代本机docker项目才能解决问题，不懂的人问都不敢问了

**Comment by missuo** [comment]
> > > > 解决了，用docker搭建好FreeGPT35后，用域名反向代理到这个3040端口，然后这么设置： ![image](https://private-user-images.githubusercontent.com/20642702/319237736-700621b3-16b5-4de0-90c6-b3f37f3aa640.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMDUwOTAsIm5iZiI6MTcxMjIwNDc5MCwicGF0aCI6Ii8yMDY0MjcwMi8zMTkyMzc3MzYtNzAwNjIxYjMtMTZiNS00ZGUwLTkwYzYtYjNmMzdmM2FhNjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDA0MjYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlNzE4NjMwNzdjNTNhYzI3YTk5ZTA0YjE4YmM1MTZkYjJlYTZhOGIxOWYxMTQ1OTU3MDM4MWYzODQwOTRkNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5mAb5_7pw4euQH3O_TeOcnHf38MgmvusdMjV3zXoAPs)
> > > 
> > > 
> > > 虽然这样是可以，但绕去多了几重呀，作者也不提醒一下
> > 
> > 
> > 我需要提醒什么？我让你这么绕来绕去的？你自己不会用怪作者？？？？**Docker Compose** 启动两个 **Services**，一键启动不就行了？自己搞不定就知道发 Issue，在这喷作者的时间，你好好把 Docker 学学明白。
> 
> 你是暗示我们天生大神，自己都懂得填写接口地址啊。楼上都要反代本机docker项目才能解决问题，不懂的人问都不敢问了

不是不让你问，是你自己搞不定就怪作者，有没有反思一下自己的问题，为什么别人可以搞得定？

**Comment by alexallen1** [comment]
我这里是问，一定要这样反代才能解决问题吗？google 全网就这一种反代解决方法。

**Comment by missuo** [comment]
> 我这里是问，一定要这样反代才能解决问题吗？google 全网就这一种反代解决方法。如果你说：是，只能这样反代解决，那大伙没话说

我说了要反代嘛？我说了不用反代码？这个 Issue 我都没发表过任何的建议，你上来就喷作者。

**Comment by alexallen1** [comment]
只是请求范例。不然只能全网等教程。不是天生直接精通大神的。

**Comment by missuo** [comment]
> 只是请求范例。不然只能全网等教程。不是天生直接精通大神的。

那你不会就虚心问就完事了，喷作者是啥意思？我能知道你想接入什么服务？这是开源项目，我得把所有可能的接入教程全给你写的明明白白了是不是？

**Comment by alexallen1** [comment]
只是看到你的回复I closed this issue directly because I think you should have read the README carefully before raising it.
如果不是给一般人看的当我走错了门。抱歉

**Comment by missuo** [comment]
> 只是看到你的回复I closed this issue directly because I think you should have read the README carefully before raising it. 如果不是给一般人看的当我走错了门。抱歉

这句话是针对这个 Issue 的，`{"status":false,"error":{"message":"The requested endpoint was not found. please make sure to use "[http://localhost:3040/v1\](http://localhost:3040/v1%5C)" as the base URL.","type":"invalid_request_error"}}`，这个的报错是因为他没有请求对路径，且没有使用 POST 请求，所以我说需要仔细阅读 README。

**Comment by missuo** [comment]
支持了一键部署 `FreeGPT35` 服务 + `ChatGPT-Next-Web`.

https://github.com/missuo/FreeGPT35#freegpt35-service-with-chatgpt-next-web

**Comment by ijrou** [comment]
> > 解决了，用docker搭建好FreeGPT35后，用域名反向代理到这个3040端口，然后这么设置： ![image](https://private-user-images.githubusercontent.com/20642702/319237736-700621b3-16b5-4de0-90c6-b3f37f3aa640.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMDUwOTAsIm5iZiI6MTcxMjIwNDc5MCwicGF0aCI6Ii8yMDY0MjcwMi8zMTkyMzc3MzYtNzAwNjIxYjMtMTZiNS00ZGUwLTkwYzYtYjNmMzdmM2FhNjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDA0MjYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlNzE4NjMwNzdjNTNhYzI3YTk5ZTA0YjE4YmM1MTZkYjJlYTZhOGIxOWYxMTQ1OTU3MDM4MWYzODQwOTRkNmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5mAb5_7pw4euQH3O_TeOcnHf38MgmvusdMjV3zXoAPs)
> 
> 虽然这样是可以，但绕去多了几重呀，作者也不提醒一下

我也是开发者，也是第一次自己搭建使用 chatgpt-next-web这玩意，就事论事这事儿也不真全怪作者，只能怪自己对仓库使用熟练度不精，有时候就是这样，要是之前弄过chatgpt-next-web的对这个问题也压根没问题了（作者以为大家都会），chatgpt-next-web只是框架，我以为我输入问题后会将请求发送到 chatgpt-next-web 后端处理后由chatgpt-next-web转发出去，没想到直接在页面就将 `你的地址` 发出去了，压根不经过 chatgpt-next-web 处理，chatgpt-next-web只是充当了纯纯的UI，，，在这之前我都一直是用docker提供的ip导致一直出现这问题： https://github.com/missuo/FreeGPT35/issues/13 刚开始我以为是是容器间网络设置问题，但是我记得默认的桥接之间容器间是可以互相通讯的，期间我也是重温了docker网络这块，又问了好多人发了好多贴都没人解答，本想着就这么算了又有点不甘，直到抄手下载  chatgpt-next-web 源码准备断点调试来着了才无意中打开浏览器控制台才发现问题所在，，，当然，要是作者善于提醒，我也能少走很多弯路不浪费时间了，，，也希望作者无视别人的怨言，共勉。。。
![image](https://github.com/missuo/FreeGPT35/assets/20642702/4b27e8bb-b2ea-4802-b82f-f46d877df746)
