### ISSUE TITLE
An error happened, please make sure your request is SFW

### ISSUE THREAD

**Issue by ysnows** [missuo/FreeGPT35#2]
{"status":false,"error":{"message":"An error happened, please make sure your request is SFW, or use a jailbreak to bypass the filter.","type":"invalid_request_error"}}

Thank you for your contribution, but I encountered some problems：

 I just downloaded the source code, then ran node app.js, and made a curl request, and then got this error.

Thanks~

**Comment by ysnows** [comment]
I change the node version to 18, then it works, thank you for your awesome project~

**Comment by missuo** [comment]
Good! 

> I change the node version to 18, then it works, thank you for your awesome project~
