### ISSUE TITLE
How to use system prompt

### ISSUE THREAD

**Issue by OmiiiDev** [missuo/FreeGPT35#23]
Does it work? If yes then how do I use it?

**Comment by missuo** [comment]
如果我没记错的话，这是你发的第二个一模一样的 Issue 了。上一个 Issue 我直接关闭了，原因是你根本就没有尝试，就问我是否支持。如果你自己尝试了我想你早就有了答案。

**Comment by missuo** [comment]
> Does it work? If yes then how do I use it?

If I remember correctly, this is the second identical issue you've posted. I closed the previous issue directly because you didn't even attempt it and just asked me if it supported it. If you had tried it yourself, I think you would have had an answer long ago.
