### ISSUE TITLE
Request support for cloudflare workers deployment

### ISSUE THREAD

**Issue by zhu327** [missuo/FreeGPT35#26]

**Comment by missuo** [comment]
I'm not sure if the outbound IP of **Cloudflare Workers** can successfully complete the request. So, there are currently no plans for adaptation.

**Comment by zhu327** [comment]
ChatGPT itself uses Cloudflare CDN. Many people also use Cloudflare Workers to proxy the GPT API, so the egress IP should be OK.

**Comment by missuo** [comment]
> ChatGPT itself uses Cloudflare CDN. Many people also use Cloudflare Workers to proxy the GPT API, so the egress IP should be OK.

That's the OpenAI API, not the web version of ChatGPT.

**Comment by anhao** [comment]
I tested it. Cloudflare workers don't work.

**Comment by 1638234804** [comment]
Works request will get this page：

![image](https://github.com/missuo/FreeGPT35/assets/27682409/76835c57-b039-4ef5-b206-0fcf65663f98)
![image](https://github.com/missuo/FreeGPT35/assets/27682409/bab247a6-e54d-4350-b0ef-84ff293a0844)

**Comment by missuo** [comment]
@anhao @1638234804 Thanks for your feedback.
