### ISSUE TITLE
能否增加个联网功能

### ISSUE THREAD

**Issue by EmperorGaozuofHan** [missuo/FreeGPT35#28]
接入成功 但是没有联网功能了

**Comment by missuo** [comment]
提问之前动动你脑子，你试试官网网站的 GPT-3.5 有联网功能？
<img width="772" alt="image" src="https://github.com/missuo/FreeGPT35/assets/55200481/e64ceef5-283f-413b-a010-dbd5450ce43c">

**Comment by EmperorGaozuofHan** [comment]
就是因为不支持 所以才写一个啊 老板
