### ISSUE TITLE
please make sure your request is SFW, or use a jailbreak to pass the filter

### ISSUE THREAD

**Issue by baiduman2020** [missuo/FreeGPT35#30]
When multiple messages are sent, {"status": false, "error": {"message": "An error happened, please make sure your request is SFW, or use a jailbreak to pass the filter.", "type": "invalid_request_error"} will appear

**Comment by dark2star** [comment]
我也遇到了同样的问题，通过抓包发现返回了403 html页面，这个问题看起来是随机的，似乎是遇到了限流。

**Comment by dangehub** [comment]
OpenAI has not banned my IP, but my server's region cannot access ChatGPT without logging in.I suspect this is the reason for the error.
