### ISSUE TITLE
Error refreshing session ID, retrying in 1 minute...

### ISSUE THREAD

**Issue by shawokou123** [missuo/FreeGPT35#4]
Error refreshing session ID, retrying in 1 minute...
If this error persists, your country may not be supported yet.
If your country was the issue, please consider using a U.S. VPN.
Request: POST /v1/chat/completions 2 messages (stream-disabled)

**Comment by H-T-H** [comment]
I have the same problem, and I am sure my US server can access chatgpt3.5.

**Comment by shawokou123** [comment]
An error happened, please make sure your request is SFW, or use a jailbreak to bypass the filter

**Comment by shawokou123** [comment]
I am sure my US server can access chatgpt3.5 
but still error:
An error happened, please make sure your request is SFW, or use a jailbreak to bypass the filter

**Comment by missuo** [comment]
How did you deploy it?

**Comment by shawokou123** [comment]
i use macos 
1、 git clone https://github.com/missuo/FreeGPT35.git
2、cd FreeGPT35
3、npm install
4、    node app.js
5、------------------
 Server is running at http://localhost:3040

🔗 Base URL: http://localhost:3040/v1
🔗 ChatCompletion Endpoint: http://localhost:3040/v1/chat/completions

📝 Original TS Source By: Pawan.Krd
📝 Modified Into JavaScript By: Adam

Error refreshing session ID, retrying in 1 minute...
If this error persists, your country may not be supported yet.
If your country was the issue, please consider using a U.S. VPN.

**Comment by missuo** [comment]
```bash
node -v
```

**Comment by shawokou123** [comment]
> ```shell
> node -v
> ```

node -v
v18.20.0

npm -v
10.5.0

**Comment by missuo** [comment]
If you are unable to use this project normally, it is most likely due to issues with your IP. Your IP has triggered Cloudflare's shield, or has already been banned. Please try to change your IP or switch servers on your own.
