### ISSUE TITLE
回答不完整，是我没设置好吗？

### ISSUE THREAD

**Issue by AndyLin2020** [missuo/FreeGPT35#40]
ChatGPT-Next-Web，稍微长点的答案（500字以内）回答不完整，再次给继续命令才能接下去，在哪里可以设置呢？

**Comment by bxworks** [comment]
我也是这个问题。继续还接不上

**Comment by AndyLin2020** [comment]
[PawanOsman](https://github.com/PawanOsman)的源码正常回答
