### ISSUE TITLE
win11下wsl2里怎么安装，调用呢？ 有谁能把命令更新一下吗？

### ISSUE THREAD

**Issue by bk111** [missuo/FreeGPT35#41]
win11下wsl2里怎么安装，调用呢？ 有谁能把命令更新一下吗？

**Comment by CellLz** [comment]
如果是ubuntu或debian系统的话，先用`sudo apt update 
sudo apt upgrade
sudo apt install docker docker-compose`
来安装docker相关组件，然后再按照此项目主页中说的运行并部署docker项目即可。
需要注意的是你的本地网络可能访问不了chatgpt，所以最好是在一台美国的服务器上把docker项目部署好以后，再从本地调用它的api

**Comment by missuo** [comment]
> 如果是ubuntu或debian系统的话，先用
> 
> `sudo apt update && sudo apt upgrade && sudo apt install docker docker-compose`
> 
> 来安装docker相关组件，然后再按照此项目主页中说的运行并部署docker项目即可。
> 
> 需要注意的是你的本地网络可能访问不了chatgpt，所以最好是在一台美国的服务器上把docker项目部署好以后，再从本地调用它的api

请注意，最新版的 Docker 不需要单独安装 Compose。

**Comment by bk111** [comment]
> 如果是ubuntu或debian系统的话，先用 `sudo apt update && sudo apt upgrade && sudo apt install docker docker-compose` 来安装docker相关组件，然后再按照此项目主页中说的运行并部署docker项目即可。 需要注意的是你的本地网络可能访问不了chatgpt，所以最好是在一台美国的服务器上把docker项目部署好以后，再从本地调用它的api

wsl里的ubuntu下安装docker后，怎么在win11里的浏览器，或者api里调用呢？

**Comment by missuo** [comment]
> > 如果是ubuntu或debian系统的话，先用 `sudo apt update && sudo apt upgrade && sudo apt install docker docker-compose` 来安装docker相关组件，然后再按照此项目主页中说的运行并部署docker项目即可。 需要注意的是你的本地网络可能访问不了chatgpt，所以最好是在一台美国的服务器上把docker项目部署好以后，再从本地调用它的api
> 
> 
> 
> wsl里的ubuntu下安装docker后，怎么在win11里的浏览器，或者api里调用呢？

Bridge Mode，在 Linux 的网络配置 DHCP 就可以了。但是我不明白你为什么非要这么折腾。Windows 不就可以跑 Docker 吗，为什么要这样复杂化？

**Comment by bk111** [comment]
> > 如果是ubuntu或debian系统的话，先用
> > `sudo apt update && sudo apt upgrade && sudo apt install docker docker-compose`
> > 来安装docker相关组件，然后再按照此项目主页中说的运行并部署docker项目即可。
> > 需要注意的是你的本地网络可能访问不了chatgpt，所以最好是在一台美国的服务器上把docker项目部署好以后，再从本地调用它的api
> 
> 请注意，最新版的 Docker 不需要单独安装 Compose。

deploy项有点看不懂，Node
npm install
node app.js

docker run -p 3040:3040 ghcr.io/missuo/freegpt35
docker run -p 3040:3040 missuo/freegpt35
Docker Compose
Only FreeGPT35 Service
mkdir freegpt35 && cd freegpt35
wget -O compose.yaml https://raw.githubusercontent.com/missuo/FreeGPT35/main/compose.yaml
docker compose up -d
这些是穿行全执行，还是

> > > 如果是ubuntu或debian系统的话，先用 `sudo apt update && sudo apt upgrade && sudo apt install docker docker-compose` 来安装docker相关组件，然后再按照此项目主页中说的运行并部署docker项目即可。 需要注意的是你的本地网络可能访问不了chatgpt，所以最好是在一台美国的服务器上把docker项目部署好以后，再从本地调用它的api
> > 
> > 
> > wsl里的ubuntu下安装docker后，怎么在win11里的浏览器，或者api里调用呢？
> 
> Bridge Mode，在 Linux 的网络配置 DHCP 就可以了。但是我不明白你为什么非要这么折腾。Windows 不就可以跑 Docker 吗，为什么要这样复杂化？

我还以为 win-docker-desk 不行呢，原来你们都是win下的docker。 那好我就直接装了。

**Comment by missuo** [comment]
如果你不懂英文可以点一下翻译，如果你是小白，我建议你别折腾了。这个文档已经写的非常清楚。

**Comment by bk111** [comment]
> 如果你不懂英文可以点一下翻译，如果你是小白，我建议你别折腾了。这个文档已经写的非常清楚。

原来你们都用的是docker-desktop， 我一直在wsl下用docker

**Comment by 1eexk** [comment]
> 如果是ubuntu或debian系统的话，先用 `sudo apt update && sudo apt upgrade && sudo apt install docker docker-compose` 来安装docker相关组件，然后再按照此项目主页中说的运行并部署docker项目即可。 需要注意的是你的本地网络可能访问不了chatgpt，所以最好是在一台美国的服务器上把docker项目部署好以后，再从本地调用它的api

不可以直接配置docker容器的代理吗？？
