### ISSUE TITLE
The requested endpoint was not found. please make sure to use \"http://localhost:3040/v1\" as the base URL.

### ISSUE THREAD

**Issue by liu-ziting** [missuo/FreeGPT35#44]
{"status":false,"error":{"message":"The requested endpoint was not found. please make sure to use \"http://localhost:3040/v1\" as the base URL.","type":"invalid_request_error"}}

**Comment by missuo** [comment]
Pls READ `README` carefully.

**Comment by Yang-yang-y** [comment]
> http://localhost:3040/v1\

use  http://IP:3040/v1/

**Comment by Yang-yang-y** [comment]
> {"status":false,"error":{"message":"The requested endpoint was not found. please make sure to use "[http://localhost:3040/v1\](http://localhost:3040/v1%5C)" as the base URL.","type":"invalid_request_error"}}

API use  "http://IP:3040/v1/"
