### ISSUE TITLE
返回内容为空

### ISSUE THREAD

**Issue by Ash-one** [missuo/FreeGPT35#48]
使用测试用例
```
curl http://ip:3040/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer any_string_you_like" \
  -d '{
    "model": "gpt-3.5-turbo",
    "messages": [
      {
        "role": "user",
        "content": "Hello!"
      }
    ],
    "stream": true
    }'
```
发现返回的内容为空
```
data: {"id":"chatcmpl-9jKHVqNoeYznlG9q6iHJE7SkNQMM","created":1713580134677,"object":"chat.completion.chunk","model":"gpt-3.5-turbo","choices":[{"delta":{"content":""},"index":0,"finish_reason":"stop"}]}
```
在其他调用该api的应用中，同样收到回复，但是内容为空，所以是OpenAI新做了限制吗？

**Comment by Ash-one** [comment]
更换了原版最新的docker镜像，同样的测试用例返回内容为`Error message from OpenAI: Our systems have detected unusual activity from your device. Please try again later.`

**Comment by AndyLin2020** [comment]
早上起来发现一样问题

**Comment by y1713375484** [comment]
<img width="898" alt="image" src="https://github.com/missuo/FreeGPT35/assets/80376536/a1f25097-665f-4aaf-ba0c-2d0900047bb7">
我还以为是我的问题呢

**Comment by jhkmichael** [comment]
一样的问题
{"id":"chatcmpl-7xvxpvCn74lNnYfHdVyUW5wIkqdM","created":1713588420219,"model":"gpt-3.5-turbo","object":"chat.completion","choices":[{"finish_reason":"stop","index":0,"message":{"content":"","role":"assistant"}}],"usage":{"prompt_tokens":0,"completion_tokens":0,"total_tokens":0}}

**Comment by zcracker** [comment]
一样的问题

**Comment by tiancool** [comment]
无法使用，同样为空

**Comment by LLilymay** [comment]
这是因为openai增加了一个新的参数OpenAI-Sentinel-Proof-Token

**Comment by Dioddo** [comment]
https://github.com/aurora-develop/aurora/commit/c7588f8041128d885fd9de07c1f0b1c4073fd601

找到一个修复的项目，作者可以跟进一下吗

**Comment by zcracker** [comment]
快修一下吧 完全宕机了 😁谢谢

**Comment by zsj1zsj** [comment]
同样的问题

**Comment by k0baya** [comment]
https://github.com/k0baya/FreeGPT35-Glitch/blob/main/app.js

glitch分支已经修复，可以参考一下这个app.js。

**Comment by missuo** [comment]
Thanks @k0baya .

Try new version. 

```bash
docker run -p 3040:3040 missuo/freegpt35
```
