### ISSUE TITLE
Error getting a new session, please try again later

### ISSUE THREAD

**Issue by equationdz** [missuo/FreeGPT35#51]
这是为什么啊??搜索不到解决方案啊..

{
  "status": false,
  "error": {
    "message": "Error getting a new session, please try again later, if the issue persists, please open an issue on the GitHub repository.",
    "type": "invalid_request_error"
  }
}

**Comment by missuo** [comment]
我希望你可以赌一下 README。

**Comment by tomridder** [comment]
> 我希望你可以仔细读一下 README。

我也遇到了相同的问题，服务器是美区服务器
nginx 也配置了 依然报错

rror getting a new session, please try again later, if the issue persists, please open an issue on the GitHub repository.

**Comment by missuo** [comment]
> 我希望你可以仔细读一下 README。


我希望你可以仔细读一下 README。

**Comment by missuo** [comment]
> > 我希望你可以仔细读一下 README。
> 
> 我也遇到了相同的问题，服务器是美区服务器 nginx 也配置了 依然报错
> 
> rror getting a new session, please try again later, if the issue persists, please open an issue on the GitHub repository.


我希望你可以仔细读一下 README。

**Comment by tomridder** [comment]
> > > 我希望你可以仔细读一下 README。
> > 
> > 
> > 我也遇到了相同的问题，服务器是美区服务器 nginx 也配置了 依然报错
> > rror getting a new session, please try again later, if the issue persists, please open an issue on the GitHub repository.
> 
> 我希望你可以仔细读一下 README。
root@RainYun-piLzbXh7:~# sudo lsof -i :3040
COMMAND     PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
docker-pr 10059 root    4u  IPv4 252248      0t0  TCP *:3040 (LISTEN)
docker-pr 10066 root    4u  IPv6 251669      0t0  TCP *:3040 (LISTEN)
root@RainYun-piLzbXh7:~# curl --location 'http://127.0.0.1:3040/v1/chat/completions' --header 'Content-Type: application/json' --header 'Authorization: Bearer sk-antshu' --data '{
        "model": "gpt-3.5-turbo",
        "messages": [{"role": "user", "content": "hello"}],
        "stream":true
}'
{"status":false,"error":{"message":"Error getting a new session, please try again later, if the issue persists, please open an issue on the GitHub repository.","type":"invalid_request_error"}}root@RainYun-piLzbXh7:~#
