### ISSUE TITLE
The requested endpoint (GET /v1/chat/completions) was not found. please make sure what are you doing now

### ISSUE THREAD

**Issue by zcracker** [missuo/FreeGPT35#56]
{
  "status": false,
  "error": {
    "message": "The requested endpoint (GET /v1/chat/completions) was not found. please make sure what are you doing now.",
    "type": "invalid_request_error"

**Comment by aaronyao** [comment]
> { "status": false, "error": { "message": "The requested endpoint (GET /v1/chat/completions) was not found. please make sure what are you doing now.", "type": "invalid_request_error"

不支持浏览器GET访问，只有POST
