### ISSUE TITLE
出现An error happened, please make sure your request is SFW, or use a jailbreak to bypass the filter

### ISSUE THREAD

**Issue by y1713375484** [missuo/FreeGPT35#6]
使用docker-composer部署，在请求时会出现
<img width="979" alt="image" src="https://github.com/missuo/FreeGPT35/assets/80376536/df4f87f0-ae6f-478f-b4ab-3d0125798ac5">

**Comment by missuo** [comment]
If you are unable to use this project normally, it is most likely due to issues with your IP. Your IP has triggered Cloudflare's shield, or has already been banned. Please try to change your IP or switch servers on your own.

**Comment by lanmuz** [comment]
哦我也是这个提示，但是我的IP用网页直接访问gpt是没有任何验证的，就好烦

**Comment by hellostronger** [comment]
我也是，网页访问返回结果截断了，但是还是能正常访问的，但是用api服务就直接sfw

**Comment by missuo** [comment]
Changing the IP address is the only solution.
