### ISSUE TITLE
可以打个广告吗？基于此技术，做了一个免费的al聊天应用,   和一些杰出的人沟通，获取智慧

### ISSUE THREAD

**Issue by mggger** [missuo/FreeGPT35#61]
地址: [Role AI Chat](https://roleai.chat/)

![ex](https://camo.githubusercontent.com/253ef7e0a9b697793a142dc50a8745425cc826a998198098740df2dfd1652298/68747470733a2f2f70722d6d79626c6f672e6f73732d636e2d68616e677a686f752e616c6979756e63732e636f6d2f755069632f6578312e706e67)

**Comment by docker-master** [comment]
能不能做个免费gpt站点用
