### ISSUE TITLE
message": "The requested endpoint (GET /v1/chat/completions) was not found. please make sure what are you doing now

### ISSUE THREAD

**Issue by Yukuiii** [missuo/FreeGPT35#62]
访问报错
{
    "status": false,
    "error": {
        "message": "The requested endpoint (GET /v1/chat/completions) was not found. please make sure what are you doing now.",
        "type": "invalid_request_error"
    }
}
是啥情况啊

**Comment by missuo** [comment]
please make sure what are you doing now
