### ISSUE TITLE
docker compose版本部署到墙外的vps上，报错{"status":false,"error":{"message":"An error happened, please make sure your request is SFW, or use a jailbreak to bypass the filte       r.","type":"invalid_request_error"}}

### ISSUE THREAD

**Issue by xiebangrong** [missuo/FreeGPT35#7]
curl http://127.0.0.1:3040/v1/chat/completions \
>   -H "Content-Type: application/json" \
>   -H "Authorization: Bearer any_string_you_like" \
>   -d '{
>     "model": "gpt-3.5-turbo",
>     "messages": [
>       {
>         "role": "user",
>         "content": "Hello!"
>       }
>     ],
>     "stream": true
>     }'
{"status":false,"error":{"message":"An error happened, please make sure your request is SFW, or use a jailbreak to bypass the filte       r.","type":"invalid_request_error"}}

**Comment by shanzhengfei** [comment]
+1

**Comment by ershiyi21** [comment]
+1

**Comment by missuo** [comment]
If you are unable to use this project normally, it is most likely due to issues with your IP. Your IP has triggered Cloudflare's shield, or has already been banned. Please try to change your IP or switch servers on your own.
