### ISSUE TITLE
support proxy[http/socks5]

### ISSUE THREAD

**Issue by passwa11** [missuo/FreeGPT35#8]
```
Request: POST /v1/chat/completions 2 messages (stream-enabled)
Error refreshing session ID, retrying in 1 minute...
If this error persists, your country may not be supported yet.
If your country was the issue, please consider using a U.S. VPN.
```

**Comment by missuo** [comment]
If you are unable to use this project normally, it is most likely due to issues with your IP. Your IP has triggered Cloudflare's shield, or has already been banned. Please try to change your IP or switch servers on your own.

**Comment by weiyideai520** [comment]
docker下 如何设置代理？
