### ISSUE TITLE
VPS deployment in the United States received an error message: Error refreshing session ID...please consider using a U.S. VPN.

### ISSUE THREAD

**Issue by SunnyGPT** [missuo/FreeGPT35#9]
I used a US VPS to deploy the container, but I still got this error message: Error refreshing session ID, retrying in 1 minute...
If this error persists, your country may not be supported yet.

**Comment by missuo** [comment]
It looks like your IP has been banned.

**Comment by SunnyGPT** [comment]
It was not blocked, but encountered cloudflare robot inspection. Is there any solution?

**Comment by missuo** [comment]
> It was not blocked, but encountered cloudflare robot inspection. Is there any solution?

Nope.
